### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by JianJuly** [Drinkhuahuaniu/INShuaKe#1]
请问项目能正常运行吗？

我这边可以读取个人积分，环境配置应该没有问题。但是报错timeout，不知道是课程网址输入不对还是什么问题？
![1708792521614](https://github.com/Drinkhuahuaniu/INShuaKe/assets/27723341/454e6d77-f24d-4848-b2ed-e03c40c3241f)

**Comment by lazypap** [comment]
我也不能正常运行，期待作者更新

**Comment by Drinkhuahuaniu** [comment]
可以正常运行的，我现在也天天都在用，只是这个是河南的哈哈，然后你们地址填的让我看看，然后你可以把这个注释一下在运行让浏览器出来看看到底哪里报错了，截个图让我看看
![image](https://github.com/Drinkhuahuaniu/INShuaKe/assets/154965552/5677866b-fbe8-41c7-a636-b1aff6b14465)
等我有空在完善个更好的

**Comment by JianJuly** [comment]
![image](https://github.com/Drinkhuahuaniu/INShuaKe/assets/27723341/4d60fae2-0ad5-4a12-b04a-02b805c5a3c9)
弹出来的是这个页面，请问课程地址输入是正确的吗？

**Comment by JianJuly** [comment]
@Drinkhuahuaniu

**Comment by Drinkhuahuaniu** [comment]
不对不对，你得找个课程的页，你看我readme.md里，课程地址是长这个样子的
![image](https://github.com/Drinkhuahuaniu/INShuaKe/assets/154965552/2fbc7307-992a-493b-bcdd-65ec92faa991)

**Comment by Drinkhuahuaniu** [comment]
你点课程中心，然后在里边找个，我记得channelld=895还有865等一堆的，我目前刷的都是这俩

**Comment by Drinkhuahuaniu** [comment]
找到课程了就把这个注释取消了，浏览器就不会弹出来在后台运行了
![image](https://github.com/Drinkhuahuaniu/INShuaKe/assets/154965552/4e2b6c33-f175-4726-9076-3d8e546a0cae)

**Comment by Drinkhuahuaniu** [comment]
@JianJuly

**Comment by JianJuly** [comment]
搞定了，跪谢老哥！！ @Drinkhuahuaniu

**Comment by Drinkhuahuaniu** [comment]
> 搞定了，跪谢老哥！！ @Drinkhuahuaniu

不 老哥，我是真弟弟，我肯定比你小

**Comment by C315703603** [comment]
![image](https://github.com/Drinkhuahuaniu/INShuaKe/assets/103497700/4b73df20-9d88-4d81-bb3e-94de8f7772f4)
大大这个怎么回事啊？

**Comment by su22cmd** [comment]
![image](https://github.com/Drinkhuahuaniu/INShuaKe/assets/71595313/eb0f8a5f-45df-42ea-bf91-a9c2fc208289)
找不到chromedriver的路径，请看README.md的环境配置的chromedriver配置
![image](https://github.com/Drinkhuahuaniu/INShuaKe/assets/71595313/7101aded-1d1a-4197-8d69-2846dcacb410)


> ![image](https://private-user-images.githubusercontent.com/103497700/311611265-4b73df20-9d88-4d81-bb3e-94de8f7772f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMDIxNjYsIm5iZiI6MTcxMDIwMTg2NiwicGF0aCI6Ii8xMDM0OTc3MDAvMzExNjExMjY1LTRiNzNkZjIwLTlkODgtNGQ4MS1iYjNlLTk0ZGU4Zjc3NzJmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQwMDA0MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMWI5OTBlMmE2MTAwOWQ2Njc3YTIyOTU0ZTViMDM3MzFkMjQ1NTRjNGViOTZhMDIwMzc0NzUwMzJlOTAwYzUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QZ17xLD2Q8xipEpZRrhz3ZhFtmrCXtVCkL1gcR-CdSA) 大大这个怎么回事啊？

**Comment by Drinkhuahuaniu** [comment]
> ![image](https://private-user-images.githubusercontent.com/103497700/311611265-4b73df20-9d88-4d81-bb3e-94de8f7772f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMDI0MzgsIm5iZiI6MTcxMDIwMjEzOCwicGF0aCI6Ii8xMDM0OTc3MDAvMzExNjExMjY1LTRiNzNkZjIwLTlkODgtNGQ4MS1iYjNlLTk0ZGU4Zjc3NzJmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQwMDA4NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OGFlNTY5NzQ3YzI3MTAzYzE5NTVkODU0Y2Q0NTAxZWRiNjc3NmUzNmQzYWM5NzE0NGMyNTI2YzIxNjIzMjdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nEAkRucwMU6QfH6blPHVCxpOfArcC0zYY5pH-O6gKWs) 大大这个怎么回事啊？

**找不到Chromedriver,请看readme.md文档把chromedriver环境配置一下**
![image](https://github.com/Drinkhuahuaniu/INShuaKe/assets/154965552/fdfcabba-6a59-4d1b-b743-8bde095a0691)

**Comment by C315703603** [comment]
![Uploading VX2KQ~AJWD@`H6QP3B@BF
![F3H$L)0DW$DD$1W}815(62S](https://github.com/Drinkhuahuaniu/INShuaKe/assets/103497700/78b59433-211e-4f59-bf7e-cb31e6891266)
9X.png…]()
![DY86P3K2S RTX}J)E}9HT_Q](https://github.com/Drinkhuahuaniu/INShuaKe/assets/103497700/1d6f31ea-9547-4fde-ba8f-3dc1d34a6854)
大大，是哪里没有设置好吗？运行后还是一样的

**Comment by C315703603** [comment]
![VX2KQ~AJWD@`H6QP3B@BF9X](https://github.com/Drinkhuahuaniu/INShuaKe/assets/103497700/d5d500fd-3e50-489f-a686-1cd6168efeac)
![F3H$L)0DW$DD$1W}815(62S](https://github.com/Drinkhuahuaniu/INShuaKe/assets/103497700/43e0a2d5-cd57-46c9-ad16-220add391f26)
![DY86P3K2S RTX}J)E}9HT_Q](https://github.com/Drinkhuahuaniu/INShuaKe/assets/103497700/ad818dfb-1e88-488d-b1b7-e822e69ede52)
大大，是哪里没有设置好吗？还是一样无法正常运行

**Comment by Drinkhuahuaniu** [comment]
> ![VX2KQ~AJWD@`H6QP3B@BF9X](https://private-user-images.githubusercontent.com/103497700/311947300-d5d500fd-3e50-489f-a686-1cd6168efeac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMjQ0MTUsIm5iZiI6MTcxMDIyNDExNSwicGF0aCI6Ii8xMDM0OTc3MDAvMzExOTQ3MzAwLWQ1ZDUwMGZkLTNlNTAtNDg5Zi1hNjg2LTFjZDYxNjhlZmVhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQwNjE1MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNmY5MWNkNDNlMWE0MjY4M2YzOGFjYjg1Njc0NjI5Nzg0NTA4ZWJkN2E1YjhiYmQ3MmRmOTJhNWQ2MDdkYzg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MCih8d2mM2td8N8oBQF9wQcqnQlew3TtwyiEbcDfWLg) ![F3H$L)0DW$DD$1W}815(62S](https://private-user-images.githubusercontent.com/103497700/311947374-43e0a2d5-cd57-46c9-ad16-220add391f26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMjQ0MTUsIm5iZiI6MTcxMDIyNDExNSwicGF0aCI6Ii8xMDM0OTc3MDAvMzExOTQ3Mzc0LTQzZTBhMmQ1LWNkNTctNDZjOS1hZDE2LTIyMGFkZDM5MWYyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQwNjE1MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDVjNDczOTJiNGQ5MjcxNzE2YjU1MDE5NGE1M2E4ZDcwNzZlOWEwNzU4NzkwMjdjNGExNDM1MDY3YzMxN2JjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C_xpZUpXrALrAf2uOAdHE6MQr1TrjxDLojDquCqTYOk) ![DY86P3K2S RTX}J)E}9HT_Q](https://private-user-images.githubusercontent.com/103497700/311947382-ad818dfb-1e88-488d-b1b7-e822e69ede52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMjQ0MTUsIm5iZiI6MTcxMDIyNDExNSwicGF0aCI6Ii8xMDM0OTc3MDAvMzExOTQ3MzgyLWFkODE4ZGZiLTFlODgtNDg4ZC1iMWI3LWU4MjJlNjllZGU1Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQwNjE1MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDk1MjhkYmYwMjBjYTUxYzU5ZGJmMTUyZmRjYmJiYjY1YjliYmU4NjAwNWMwZjQzMWRjYmM4YmE5MTJjNDYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CaoeaY0kb9xVP5kE4_Q5FQpay7dOeecR9R64C08jblY) 大大，是哪里没有设置好吗？下载的是同一个版本的chrome以及chromedriver，也添加了环境变量，confing里也改变了chromedriver路径。还是一样无法正常运行

换成./chrome/chromedriver.exe 试一下
![image](https://github.com/Drinkhuahuaniu/INShuaKe/assets/154965552/54d2fcd5-0ee1-4367-ad8e-6d32dc173add)

**Comment by C315703603** [comment]
还是一样不行

**Comment by Drinkhuahuaniu** [comment]
> 还是一样不行

把报错的给我看一下

**Comment by C315703603** [comment]
![1710238660583](https://github.com/Drinkhuahuaniu/INShuaKe/assets/103497700/c8478616-7bef-4327-948b-bb2f7f2b227e)

**Comment by Drinkhuahuaniu** [comment]
> ![1710238660583](https://private-user-images.githubusercontent.com/103497700/312037038-c8478616-7bef-4327-948b-bb2f7f2b227e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMzkwMDIsIm5iZiI6MTcxMDIzODcwMiwicGF0aCI6Ii8xMDM0OTc3MDAvMzEyMDM3MDM4LWM4NDc4NjE2LTdiZWYtNDMyNy05NDhiLWJiMmY3ZjJiMjI3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQxMDE4MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjk2YTYzZTQ0ZjVjZjUwZmFlYzI1YjEyYzY1NDk4Mzc4ODE0NmQ5MTliZDUwMDZkYzY3YjQ5N2NmNzk2ZTQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9gjLJ1MWLgzNpPnLURyxbV71CtNfDtyLV0Rj9RDcbho)

好哥们啊，我终于看懂了，你这是找不到chrome，你的环境变量加错地方了，应该是加到PATH里
![image](https://github.com/Drinkhuahuaniu/INShuaKe/assets/154965552/87a99890-2f2d-4cea-8391-43c572e260bb)
如下图
![image](https://github.com/Drinkhuahuaniu/INShuaKe/assets/154965552/f275c1d5-cc26-4401-940e-4420063011a6)

**Comment by C315703603** [comment]
已经调好了，完美运行，谢谢大大了！

**Comment by Drinkhuahuaniu** [comment]
> 已经调好了，完美运行，谢谢大大了！

no thinks
